version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
